### ISSUE TITLE
Doesn’t integrate with SmartThings Home Monitor

### ISSUE THREAD

**Issue by sparky2708** [rtorchia/DSC-Envisalink#5]
This doesn’t seem to integrate with the SmartThings smart app for monitoring your home: “SmartThings Home Monitor”. When the DSC alarm is armed the status in “SmartThings Home Monitor” doesn’t change, it seems to always show “Disarmed”.

**Comment by rtorchia** [comment]
The STHM doesn't response to a change in status from a device, in this case the DSC Panel (Stay or Away). This is due to a change in SmartThings in the new app and is a bug/feature.
You have to setup an automation for the STHM to sync properly.
If you use the STHM to arm/disarm, then the DSC Panel will respond to accordingly.
